### ISSUE TITLE
Separate Login and SignUp Screens

### ISSUE THREAD

**Issue by shinjigu** [Winter-Zzzz/client#14]
### **Purpose**
- Splitting the combined Login and SignUp screen into two separate screens for better navigation and user clarity.

### **Task**
- [x] Install react-router-dom package
- [x] Configure routing setup in App.js
- [x] Add navigation links between Login and SignUp pages
- [x] Connect to AddDevice.js when logged in
- [x] Navigate to main page automatically if user is authenticated
