### ISSUE TITLE
Implement Device Control and Management System

### ISSUE THREAD

**Issue by shinjigu** [Winter-Zzzz/client#23]
### **Purpose**
- Create device control interface for managing device settings

### **Task**
- [x] Create device control feedback UI
- [x] Implement device control functions
- [x] Add device control access in DeviceList screen
