### ISSUE TITLE
Improve Device Control

### ISSUE THREAD

**Issue by shinjigu** [Winter-Zzzz/client#34]
### **Purpose**
Add function execution capabilities to existing device control interface using device QR code data

### **Task**
- [x] Parse device functions from QR code JSON data
- [x] Create input fields for function parameters
- [x] Add function execution button
- [x] Implement function execution handler
- [x] Create feedback UI for function execution result
