### ISSUE TITLE
Make Entry & Tutorial Screen

### ISSUE THREAD

**Issue by shinjigu** [Winter-Zzzz/client#43]
### **Purpose**
To welcome users and provide a brief introduction to MatterTunnel's features and usage instructions before the login screen

### **Task**
- [x] Implement Entry Screen
- [x] Implement Tutorial Screen
- [x] Connect Entry-Tutorial-Login screens
