### ISSUE TITLE
Save Login State #3

### ISSUE THREAD

**Issue by jisusin** [Winter-Zzzz/client#5]
### **Purpose**
- Implement global login state management with Redux and persist the state in localStorage for seamless user experience

### **Task**
- [ ] Create auth reducer for Redux store
- [ ] Set up login state in localStorage
- [ ] Load login state on app start
