### ISSUE TITLE
Save Login State

### ISSUE THREAD

**Issue by shinjigu** [Winter-Zzzz/client#6]
### **Purpose**
- Implement global login state management with Redux and persist the state in localStorage for seamless user experience

### **Task**
- [x] Create auth reducer for Redux store
- [x] Set up login state in localStorage
- [x] Load login state on app start
