### ISSUE TITLE
User Authentication Design Integration

### ISSUE THREAD

**Issue by shinjigu** [Winter-Zzzz/client#9]
### **Purpose**
- Unifying authentication-related component styles for consistent user experience
- Consolidating redundant CSS modules into a single auth module

### **Task**
- [x] Merge Login.module.css and SignUp.module.css into auth.module.css
- [x] Update component style references in Login.js and SignUp.js
- [x] Remove deprecated CSS module files
